// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHBxMfYKZvLxvRTygOKPTDs6beOdVJcE',
    appId: '1:628991235810:web:f363cd4cca0aa9245cb0bb',
    messagingSenderId: '628991235810',
    projectId: 'superai-61980',
    authDomain: 'superai-61980.firebaseapp.com',
    storageBucket: 'superai-61980.appspot.com',
    measurementId: 'G-1BH99SCZ6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlDkaNcRaLFpr3_J5EzpzEBerqRl0xOw',
    appId: '1:628991235810:android:c5ce44ed92efa2f55cb0bb',
    messagingSenderId: '628991235810',
    projectId: 'superai-61980',
    storageBucket: 'superai-61980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUff5kFkrZtHjhpVuMq4lsaCU8JNB8k4',
    appId: '1:628991235810:ios:df913960b432cbde5cb0bb',
    messagingSenderId: '628991235810',
    projectId: 'superai-61980',
    storageBucket: 'superai-61980.appspot.com',
    iosBundleId: 'com.example.flutterapp.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMUff5kFkrZtHjhpVuMq4lsaCU8JNB8k4',
    appId: '1:628991235810:ios:640f419dcb083b765cb0bb',
    messagingSenderId: '628991235810',
    projectId: 'superai-61980',
    storageBucket: 'superai-61980.appspot.com',
    iosBundleId: 'com.example.flutterapp.flutterapp.RunnerTests',
  );
}
